In [21]:
!pip install -q kagglehub

In [2]:
import kagglehub

path = kagglehub.dataset_download("ismetsemedov/transactions")

print("Dataset path:", path)

Downloading to /root/.cache/kagglehub/datasets/ismetsemedov/transactions/1.archive...

100%|██████████| 754M/754M [00:11<00:00, 69.4MB/s]

Extracting files...

Dataset path: /root/.cache/kagglehub/datasets/ismetsemedov/transactions/versions/1

In [3]:
import os

file_path = f"{path}/synthetic_fraud_data.csv"

print(os.path.getsize(file_path) / (1024**3), "GB")

2.732716515660286 GB

In [4]:
import os
import kagglehub

path = kagglehub.dataset_download("ismetsemedov/transactions")

print(os.listdir(path))

['synthetic_fraud_data.csv']

In [5]:
file_path = f"{path}/synthetic_fraud_data.csv"

In [6]:
import pandas as pd

sample = pd.read_csv(file_path, nrows=10000)

print(sample.shape)
print(sample.columns.tolist())
sample.head()

(10000, 24)
['transaction_id', 'customer_id', 'card_number', 'timestamp', 'merchant_category', 'merchant_type', 'merchant', 'amount', 'currency', 'country', 'city', 'city_size', 'card_type', 'card_present', 'device', 'channel', 'device_fingerprint', 'ip_address', 'distance_from_home', 'high_risk_merchant', 'transaction_hour', 'weekend_transaction', 'velocity_last_hour', 'is_fraud']

,transaction_id,customer_id,card_number,timestamp,merchant_category,merchant_type,merchant,amount,currency,country,...,device,channel,device_fingerprint,ip_address,distance_from_home,high_risk_merchant,transaction_hour,weekend_transaction,velocity_last_hour,is_fraud
0,TX_a0ad2a2a,CUST_72886,6646734767813109,2024-09-30 00:00:01.034820+00:00,Restaurant,fast_food,Taco Bell,294.87,GBP,UK,...,iOS App,mobile,e8e6160445c935fd0001501e4cbac8bc,197.153.60.199,0,False,0,False,"{'num_transactions': 1197, 'total_amount': 334...",False
1,TX_3599c101,CUST_70474,376800864692727,2024-09-30 00:00:01.764464+00:00,Entertainment,gaming,Steam,3368.97,BRL,Brazil,...,Edge,web,a73043a57091e775af37f252b3a32af9,208.123.221.203,1,True,0,False,"{'num_transactions': 509, 'total_amount': 2011...",True
2,TX_a9461c6d,CUST_10715,5251909460951913,2024-09-30 00:00:02.273762+00:00,Grocery,physical,Whole Foods,102582.38,JPY,Japan,...,Firefox,web,218864e94ceaa41577d216b149722261,10.194.159.204,0,False,0,False,"{'num_transactions': 332, 'total_amount': 3916...",False
3,TX_7be21fc4,CUST_16193,376079286931183,2024-09-30 00:00:02.297466+00:00,Gas,major,Exxon,630.60,AUD,Australia,...,iOS App,mobile,70423fa3a1e74d01203cf93b51b9631d,17.230.177.225,0,False,0,False,"{'num_transactions': 764, 'total_amount': 2201...",False
4,TX_150f490b,CUST_87572,6172948052178810,2024-09-30 00:00:02.544063+00:00,Healthcare,medical,Medical Center,724949.27,NGN,Nigeria,...,Chrome,web,9880776c7b6038f2af86bd4e18a1b1a4,136.241.219.151,1,False,0,False,"{'num_transactions': 218, 'total_amount': 4827...",True

In [7]:
chunk_size = 100000

for chunk in pd.read_csv(file_path, chunksize=chunk_size):
    print(chunk.shape)
    break

(100000, 24)

In [8]:
sample = pd.read_csv(file_path, nrows=10000)

print("Shape:", sample.shape)
print("\nColumns:")
print(sample.columns.tolist())

print("\nData types:")
print(sample.dtypes)

print("\nMissing values:")
print(sample.isnull().sum())

print("\nFirst 5 rows:")
display(sample.head())

Shape: (10000, 24)

Columns:
['transaction_id', 'customer_id', 'card_number', 'timestamp', 'merchant_category', 'merchant_type', 'merchant', 'amount', 'currency', 'country', 'city', 'city_size', 'card_type', 'card_present', 'device', 'channel', 'device_fingerprint', 'ip_address', 'distance_from_home', 'high_risk_merchant', 'transaction_hour', 'weekend_transaction', 'velocity_last_hour', 'is_fraud']

Data types:
transaction_id          object
customer_id             object
card_number              int64
timestamp               object
merchant_category       object
merchant_type           object
merchant                object
amount                 float64
currency                object
country                 object
city                    object
city_size               object
card_type               object
card_present              bool
device                  object
channel                 object
device_fingerprint      object
ip_address              object
distance_from_home       int64
high_risk_merchant        bool
transaction_hour         int64
weekend_transaction       bool
velocity_last_hour      object
is_fraud                  bool
dtype: object

Missing values:
transaction_id         0
customer_id            0
card_number            0
timestamp              0
merchant_category      0
merchant_type          0
merchant               0
amount                 0
currency               0
country                0
city                   0
city_size              0
card_type              0
card_present           0
device                 0
channel                0
device_fingerprint     0
ip_address             0
distance_from_home     0
high_risk_merchant     0
transaction_hour       0
weekend_transaction    0
velocity_last_hour     0
is_fraud               0
dtype: int64

First 5 rows:

,transaction_id,customer_id,card_number,timestamp,merchant_category,merchant_type,merchant,amount,currency,country,...,device,channel,device_fingerprint,ip_address,distance_from_home,high_risk_merchant,transaction_hour,weekend_transaction,velocity_last_hour,is_fraud
0,TX_a0ad2a2a,CUST_72886,6646734767813109,2024-09-30 00:00:01.034820+00:00,Restaurant,fast_food,Taco Bell,294.87,GBP,UK,...,iOS App,mobile,e8e6160445c935fd0001501e4cbac8bc,197.153.60.199,0,False,0,False,"{'num_transactions': 1197, 'total_amount': 334...",False
1,TX_3599c101,CUST_70474,376800864692727,2024-09-30 00:00:01.764464+00:00,Entertainment,gaming,Steam,3368.97,BRL,Brazil,...,Edge,web,a73043a57091e775af37f252b3a32af9,208.123.221.203,1,True,0,False,"{'num_transactions': 509, 'total_amount': 2011...",True
2,TX_a9461c6d,CUST_10715,5251909460951913,2024-09-30 00:00:02.273762+00:00,Grocery,physical,Whole Foods,102582.38,JPY,Japan,...,Firefox,web,218864e94ceaa41577d216b149722261,10.194.159.204,0,False,0,False,"{'num_transactions': 332, 'total_amount': 3916...",False
3,TX_7be21fc4,CUST_16193,376079286931183,2024-09-30 00:00:02.297466+00:00,Gas,major,Exxon,630.60,AUD,Australia,...,iOS App,mobile,70423fa3a1e74d01203cf93b51b9631d,17.230.177.225,0,False,0,False,"{'num_transactions': 764, 'total_amount': 2201...",False
4,TX_150f490b,CUST_87572,6172948052178810,2024-09-30 00:00:02.544063+00:00,Healthcare,medical,Medical Center,724949.27,NGN,Nigeria,...,Chrome,web,9880776c7b6038f2af86bd4e18a1b1a4,136.241.219.151,1,False,0,False,"{'num_transactions': 218, 'total_amount': 4827...",True

In [9]:
sample['is_fraud'].value_counts()
sample['is_fraud'].value_counts(normalize=True)

is_fraud
False    0.5684
True     0.4316
Name: proportion, dtype: float64

In [10]:
df = sample

In [11]:
print(df)

     transaction_id customer_id       card_number  \
0       TX_a0ad2a2a  CUST_72886  6646734767813109
1       TX_3599c101  CUST_70474   376800864692727
2       TX_a9461c6d  CUST_10715  5251909460951913
3       TX_7be21fc4  CUST_16193   376079286931183
4       TX_150f490b  CUST_87572  6172948052178810
...             ...         ...               ...
9995    TX_9ceaf3bb  CUST_45006  4985387758890299
9996    TX_f3df979c  CUST_47414  6336417729353449
9997    TX_2ca220cf  CUST_28696  4000593444921742
9998    TX_25151235  CUST_99261  5533338735360330
9999    TX_c0c87cd6  CUST_71169  5765100633727195

                             timestamp merchant_category merchant_type  \
0     2024-09-30 00:00:01.034820+00:00        Restaurant     fast_food
1     2024-09-30 00:00:01.764464+00:00     Entertainment        gaming
2     2024-09-30 00:00:02.273762+00:00           Grocery      physical
3     2024-09-30 00:00:02.297466+00:00               Gas         major
4     2024-09-30 00:00:02.544063+00:00        Healthcare       medical
...                                ...               ...           ...
9995  2024-09-30 01:33:17.491908+00:00        Healthcare      pharmacy
9996  2024-09-30 01:33:17.673590+00:00            Retail      physical
9997  2024-09-30 01:33:17.746677+00:00        Restaurant     fast_food
9998  2024-09-30 01:33:17.941767+00:00         Education      supplies
9999  2024-09-30 01:33:18.385968+00:00        Restaurant     fast_food

            merchant     amount currency    country  ...           device  \
0          Taco Bell     294.87      GBP         UK  ...          iOS App
1              Steam    3368.97      BRL     Brazil  ...             Edge
2        Whole Foods  102582.38      JPY      Japan  ...          Firefox
3              Exxon     630.60      AUD  Australia  ...          iOS App
4     Medical Center  724949.27      NGN    Nigeria  ...           Chrome
...              ...        ...      ...        ...  ...              ...
9995      DuaneReade     415.93      EUR     France  ...           Safari
9996          Costco  819200.52      NGN    Nigeria  ...  Magnetic Stripe
9997     Burger King    6485.38      RUB     Russia  ...             Edge
9998  Barnes & Noble    2963.58      SGD  Singapore  ...      Chip Reader
9999     Burger King    1641.31      MXN     Mexico  ...           Safari

     channel                device_fingerprint       ip_address  \
0     mobile  e8e6160445c935fd0001501e4cbac8bc   197.153.60.199
1        web  a73043a57091e775af37f252b3a32af9  208.123.221.203
2        web  218864e94ceaa41577d216b149722261   10.194.159.204
3     mobile  70423fa3a1e74d01203cf93b51b9631d   17.230.177.225
4        web  9880776c7b6038f2af86bd4e18a1b1a4  136.241.219.151
...      ...                               ...              ...
9995     web  fb43502e0364d123ca7d78942acab5d5      59.30.58.38
9996     pos  92af51952c08f363af55e7ff0e4029b9     34.96.87.244
9997     web  7d8e711902d8e262bd0de0ba61583a37   227.150.172.65
9998     pos  5f8a5b5376c3e4cab0937530d2ad8c32     59.12.243.11
9999     web  1c1d0eba72b93989e79ed8c98fa2c90b     86.177.82.75

     distance_from_home high_risk_merchant transaction_hour  \
0                     0              False                0
1                     1               True                0
2                     0              False                0
3                     0              False                0
4                     1              False                0
...                 ...                ...              ...
9995                  0              False                1
9996                  1              False                1
9997                  0              False                1
9998                  1              False                1
9999                  1              False                1

     weekend_transaction                                 velocity_last_hour  \
0                  False  {'num_transactions': 1197, 'total_amount': 334...
1                  False  {'num_transactions': 509, 'total_amount': 2011...
2                  False  {'num_transactions': 332, 'total_amount': 3916...
3                  False  {'num_transactions': 764, 'total_amount': 2201...
4                  False  {'num_transactions': 218, 'total_amount': 4827...
...                  ...                                                ...
9995               False  {'num_transactions': 848, 'total_amount': 3315...
9996               False  {'num_transactions': 956, 'total_amount': 3613...
9997               False  {'num_transactions': 1263, 'total_amount': 769...
9998               False  {'num_transactions': 1558, 'total_amount': 444...
9999               False  {'num_transactions': 87, 'total_amount': 12910...

      is_fraud
0        False
1         True
2        False
3        False
4         True
...        ...
9995     False
9996      True
9997     False
9998      True
9999     False

[10000 rows x 24 columns]

In [12]:
import ast

df['velocity_last_hour'] = df['velocity_last_hour'].apply(ast.literal_eval)

df['velocity_transactions'] = df['velocity_last_hour'].apply(
    lambda x: x['num_transactions']
)

df['velocity_amount'] = df['velocity_last_hour'].apply(
    lambda x: x['total_amount']
)

df.drop('velocity_last_hour', axis=1, inplace=True)

In [13]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

df['year'] = df['timestamp'].dt.year
df['month'] = df['timestamp'].dt.month
df['day'] = df['timestamp'].dt.day
df['day_of_week'] = df['timestamp'].dt.dayofweek

df.drop('timestamp', axis=1, inplace=True)

In [14]:
drop_cols = [
    'transaction_id',
    'customer_id',
    'card_number',
    'device_fingerprint',
    'ip_address'
]

df.drop(columns=drop_cols, inplace=True)

In [15]:
X = df.drop('is_fraud', axis=1)
y = df['is_fraud'].astype(int)

In [16]:
print(X.shape)
print(X.dtypes)
print(X.isnull().sum())

(10000, 22)
merchant_category         object
merchant_type             object
merchant                  object
amount                   float64
currency                  object
country                   object
city                      object
city_size                 object
card_type                 object
card_present                bool
device                    object
channel                   object
distance_from_home         int64
high_risk_merchant          bool
transaction_hour           int64
weekend_transaction         bool
velocity_transactions      int64
velocity_amount          float64
year                       int32
month                      int32
day                        int32
day_of_week                int32
dtype: object
merchant_category        0
merchant_type            0
merchant                 0
amount                   0
currency                 0
country                  0
city                     0
city_size                0
card_type                0
card_present             0
device                   0
channel                  0
distance_from_home       0
high_risk_merchant       0
transaction_hour         0
weekend_transaction      0
velocity_transactions    0
velocity_amount          0
year                     0
month                    0
day                      0
day_of_week              0
dtype: int64

In [17]:
print(y.value_counts())
print(y.value_counts(normalize=True) * 100)

is_fraud
0    5684
1    4316
Name: count, dtype: int64
is_fraud
0    56.84
1    43.16
Name: proportion, dtype: float64

In [18]:
categorical_cols = X.select_dtypes(include='object').columns

for col in categorical_cols:
    print(col, X[col].nunique())

merchant_category 8
merchant_type 17
merchant 105
currency 11
country 12
city 11
city_size 2
card_type 5
device 9
channel 3

In [19]:
df = df.sort_values(['year', 'month', 'day'])

split = int(len(df) * 0.8)

train = df.iloc[:split]
test = df.iloc[split:]

In [22]:
X_train = train.drop('is_fraud', axis=1)
y_train = train['is_fraud'].astype(int)

X_test = test.drop('is_fraud', axis=1)
y_test = test['is_fraud'].astype(int)

Preprocessing

In [23]:
import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [24]:
categorical_cols = [
    'merchant_category',
    'merchant_type',
    'merchant',
    'currency',
    'country',
    'city',
    'city_size',
    'card_type',
    'device',
    'channel'
]

numerical_cols = [
    'amount',
    'distance_from_home',
    'transaction_hour',
    'velocity_transactions',
    'velocity_amount',
    'year',
    'month',
    'day',
    'day_of_week'
]

boolean_cols = [
    'card_present',
    'high_risk_merchant',
    'weekend_transaction'
]

In [25]:
for col in boolean_cols:
    X_train[col] = X_train[col].astype(int)
    X_test[col] = X_test[col].astype(int)

In [26]:
numerical_cols += boolean_cols

Preprocessing pipeline

In [27]:
numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(
        handle_unknown='ignore',
        sparse_output=True
    ))
])

In [28]:
preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

Apply preprocessing

In [29]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [30]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [33]:
X_train_processed

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 136000 stored elements and shape (8000, 195)>

cross validation

In [34]:
from sklearn.model_selection import TimeSeriesSplit, cross_validate
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# 5-fold time-series cross-validation
cv = TimeSeriesSplit(n_splits=5)

In [35]:
models = {

    'Logistic Regression': LogisticRegression(
        max_iter=1000,
        class_weight='balanced',
        random_state=42
    ),

    'Random Forest': RandomForestClassifier(
        n_estimators=200,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1
    ),

    'XGBoost': XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    )
}

In [36]:
pipelines = {}

for name, model in models.items():

    pipelines[name] = Pipeline([
        ('preprocessor', preprocessor),
        ('model', model)
    ])

In [37]:
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc',
    'pr_auc': 'average_precision'
}

results = {}

for name, pipeline in pipelines.items():

    scores = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1
    )

    results[name] = {
        'Accuracy': scores['test_accuracy'].mean(),
        'Precision': scores['test_precision'].mean(),
        'Recall': scores['test_recall'].mean(),
        'F1': scores['test_f1'].mean(),
        'ROC-AUC': scores['test_roc_auc'].mean(),
        'PR-AUC': scores['test_pr_auc'].mean()
    }

In [38]:
results_df = pd.DataFrame(results).T

print(results_df.round(4))

                     Accuracy  Precision  Recall      F1  ROC-AUC  PR-AUC
Logistic Regression    0.8941     0.8196  0.9085  0.8613   0.9586  0.9408
Random Forest          0.9131     0.9285  0.8271  0.8744   0.9730  0.9598
XGBoost                0.9331     0.9326  0.8768  0.9034   0.9800  0.9707

XGboost hyperparameter tunning

In [39]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit
from scipy.stats import randint, uniform

# 5-fold time-series cross-validation
cv = TimeSeriesSplit(n_splits=5)

# XGBoost
xgb = XGBClassifier(
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)

# Complete pipeline
xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', xgb)
])

# Hyperparameter search space
param_distributions = {
    'model__n_estimators': randint(100, 500),
    'model__max_depth': randint(3, 10),
    'model__learning_rate': uniform(0.01, 0.19),
    'model__subsample': uniform(0.6, 0.4),
    'model__colsample_bytree': uniform(0.6, 0.4),
    'model__min_child_weight': randint(1, 10),
    'model__gamma': uniform(0, 0.5)
}

# Randomized hyperparameter tuning
random_search = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=param_distributions,
    n_iter=30,
    scoring='average_precision',   # PR-AUC
    cv=cv,
    verbose=2,
    random_state=42,
    n_jobs=-1,
    return_train_score=False
)

# Train
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('scaler',
                                                                                                StandardScaler())]),
                                                                               ['amount',
                                                                                'distance_from_home',
                                                                                'transaction_hour',
                                                                                'velocity_transactions',
                                                                                'velocity_amo...
                                        'model__min_child_weight': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x782faa4f1bd0>,
                                        'model__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x782faa9ed400>,
                                        'model__subsample': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x782faa4f1e50>},
                   random_state=42, scoring='average_precision', verbose=2)

In [40]:
print("Best Parameters:")
print(random_search.best_params_)

print("\nBest CV PR-AUC:")
print(random_search.best_score_)

Best Parameters:
{'model__colsample_bytree': np.float64(0.9329770563201687), 'model__gamma': np.float64(0.10616955533913808), 'model__learning_rate': np.float64(0.04454674376934912), 'model__max_depth': 7, 'model__min_child_weight': 1, 'model__n_estimators': 413, 'model__subsample': np.float64(0.8099025726528951)}

Best CV PR-AUC:
0.971016540850337

In [41]:
best_xgb = random_search.best_estimator_

In [42]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

y_pred = best_xgb.predict(X_test)
y_prob = best_xgb.predict_proba(X_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))
print("PR-AUC   :", average_precision_score(y_test, y_prob))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy : 0.9315
Precision: 0.9376579612468408
Recall   : 0.9464285714285714
F1 Score : 0.9420228523063902
ROC-AUC  : 0.9854430850009906
PR-AUC   : 0.9901705951488005

Confusion Matrix:
[[ 750   74]
 [  63 1113]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       824
           1       0.94      0.95      0.94      1176

    accuracy                           0.93      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.93      0.93      0.93      2000

In [43]:
# Check class distribution in training data
print(y_train.value_counts())

is_fraud
0    4860
1    3140
Name: count, dtype: int64

In [44]:
negative = (y_train == 0).sum()
positive = (y_train == 1).sum()

scale_pos_weight = negative / positive

print("Non-fraud:", negative)
print("Fraud:", positive)
print("scale_pos_weight:", scale_pos_weight)

Non-fraud: 4860
Fraud: 3140
scale_pos_weight: 1.5477707006369428

In [45]:
scale_pos_weight = 1.5477707006369428

In [47]:
xgb = XGBClassifier(
    eval_metric='logloss',
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

In [48]:
xgb = XGBClassifier(
    eval_metric='logloss',
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', xgb)
])

In [49]:
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('scaler',
                                                                                                StandardScaler())]),
                                                                               ['amount',
                                                                                'distance_from_home',
                                                                                'transaction_hour',
                                                                                'velocity_transactions',
                                                                                'velocity_amo...
                                        'model__min_child_weight': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x782faa4f1bd0>,
                                        'model__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x782faa9ed400>,
                                        'model__subsample': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x782faa4f1e50>},
                   random_state=42, scoring='average_precision', verbose=2)

In [50]:
y_train.value_counts()

is_fraud
0    4860
1    3140
Name: count, dtype: int64

In [51]:
print("Best Parameters:")
print(random_search.best_params_)

print("Best CV PR-AUC:")
print(random_search.best_score_)

Best Parameters:
{'model__colsample_bytree': np.float64(0.9329770563201687), 'model__gamma': np.float64(0.10616955533913808), 'model__learning_rate': np.float64(0.04454674376934912), 'model__max_depth': 7, 'model__min_child_weight': 1, 'model__n_estimators': 413, 'model__subsample': np.float64(0.8099025726528951)}
Best CV PR-AUC:
0.971016540850337

In [52]:
y_pred = best_xgb.predict(X_test)
y_prob = best_xgb.predict_proba(X_test)[:, 1]

In [53]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

# Predictions
y_pred = best_xgb.predict(X_test)

# Probability of fraud (class 1)
y_prob = best_xgb.predict_proba(X_test)[:, 1]

# Metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)
pr_auc = average_precision_score(y_test, y_prob)

# Print results
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print("ROC-AUC  :", roc_auc)
print("PR-AUC   :", pr_auc)

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy : 0.9315
Precision: 0.9376579612468408
Recall   : 0.9464285714285714
F1 Score : 0.9420228523063902
ROC-AUC  : 0.9854430850009906
PR-AUC   : 0.9901705951488005

Confusion Matrix:
[[ 750   74]
 [  63 1113]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       824
           1       0.94      0.95      0.94      1176

    accuracy                           0.93      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.93      0.93      0.93      2000

Pipleline

In [54]:
import joblib

joblib.dump(best_xgb, "fraud_detection_model.pkl")

print("Model saved successfully")

Model saved successfully

In [55]:
import os

print(os.path.exists("fraud_detection_model.pkl"))

True

In [56]:
model = joblib.load("fraud_detection_model.pkl")

print("Model loaded successfully")

Model loaded successfully

In [57]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[0 1 0 1 1 1 1 1 0 1]